apiVersion: apps/v1
# extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trusty4ds.fullname" . }}
  labels:
    app: {{ template "trusty4ds.name" . }}
    chart: {{ template "trusty4ds.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "trusty4ds.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "trusty4ds.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: config
        configMap:
          name: {{ template "trusty4ds.fullname" . }}
      - name: scripts
        configMap:
          name: 'scripts-{{ template "trusty4ds.fullname" . }}'
          defaultMode: 0755
      - name: data
        emptyDir: {}
      - name: fusedev
        hostPath:
          path: /dev/fuse
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
          - mountPath: /etc/config/database.yaml
            name: config
            subPath: database.yaml
          - mountPath: /opt/app/.ssh/authorized_keys
            name: config
            subPath: authorized_keys
          - mountPath: /usr/local/bin/start
            name: scripts
            subPath: container_start
          - mountPath: /opt/app/run
            name: data
          - mountPath: /dev/fuse
            name: fusedev
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/start
          securityContext:
            privileged: true
            # Unfortunately fuse refuses to mount with those caps:
            # NOTE: maybe mknod inside container and try like that?
            # capabilities:
            #   add:
            #     - SYS_ADMIN
            #     - SYS_RESOURCE
            #     - MKNOD
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
