apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trusty4ds.fullname" . }}
  labels:
    app: {{ template "trusty4ds.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  yandex_passwd: {{ .Values.yadisk.passwd | b64enc | quote }}
