apiVersion: v1
kind: Service
metadata:
  name: {{ template "trusty4ds.fullname" . }}
  labels:
    app: {{ template "trusty4ds.name" . }}
    chart: {{ template "trusty4ds.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "trusty4ds.name" . }}
    release: {{ .Release.Name }}
