apiVersion: v1
kind: Service
metadata:
  name: {{ template "guacamole.fullname" . }}-guacamole
  labels:
    app: {{ template "guacamole.name" . }}
    component: guacamole
    chart: {{ template "guacamole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "guacamole.name" . }}
    component: guacamole
    release: {{ .Release.Name }}
