apiVersion: v1
kind: Service
metadata:
  name: {{ template "guacamole.fullname" . }}-guacd
  labels:
    app: {{ template "guacamole.name" . }}
    component: guacd
    chart: {{ template "guacamole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.guacd.servicePort }}
      targetPort: 4822
      protocol: TCP
      name: guacd
  selector:
    app: {{ template "guacamole.name" . }}
    component: guacd
    release: {{ .Release.Name }}
