# Default values for guacamole.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

guacd:
  image:
    repository: guacamole/guacd
    tag: 0.9.14
    pullPolicy: IfNotPresent
  servicePort: 4822
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

guacamole:
  image:
    repository: guacamole/guacamole
    tag: 0.9.14
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

mariadb:
  enabled: true
  mariadbDatabase: guacamole
  mariadbUser: guacamole
  mariadbPassword: guacamole-secret123
  mariadbRootPassword: root-secret123
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 4Gi
