replicaCount: 1

image:
  repository: voobscout/trusty4ds
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC1O9r2vhqQdUZNHpYI8HfdHk6unygQT+X4pAqqHmuSd2tSRbmqyB9bOAKACFdPvYmg+ujdVk8qAMe/XNgh/p0CmbPGnNXSrU+jvvRwon4o7LEZ3SRGDPFqrevU8kehRtXwR0bGt4zbAqRyroFH2x5h7BoKDS6yo7G0ufJ177TIGQ== ExampleKey

# persistence:
#   storageClass:
#   size: 10Gi
#   accessMode: ReadWriteOnce

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

zerotierone:
  networks: []
  private_key:

mariadb:
  enabled: true
  auth:
    rootPassword:
    database:
    username:
    password:
  persistence:
    enabled: false
