apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "zerotier.fullname" . }}
  labels:
    app: {{ template "zerotier.name" . }}
    chart: {{ template "zerotier.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zerotier.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "zerotier.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: tundev
        hostPath:
          path: /dev/net/tun
      - name: zt-identity
        secret:
          secretName: {{ template "zerotier.fullname" . }}
      - name: zt-networks
        configMap:
          name: {{ template "zerotier.fullname" . }}
          defaultMode: 0755
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          stdin: true
          tty: true
          command: ["/usr/bin/dumb-init"]
          args: ["/usr/bin/join_zt_networks"]
          volumeMounts:
          - mountPath: /var/lib/zerotier-one/identity.secret
            name: zt-identity
            subPath: zt_private_key
          - mountPath: /usr/bin/join_zt_networks
            name: zt-networks
            subPath: zt_networks
          - mountPath: /dev/net/tun
            name: tundev
          {{- if .Values.zt_api_key }}
          env:
            - name: ZT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "zerotier.fullname" . }}
                  key: zt_api_key
          {{- end }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - ps aux | grep -i '[z]erotier'
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - zerotier-cli listnetworks | grep OK
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
