apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zerotier.fullname" . }}
  labels:
    app: {{ template "zerotier.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.zt_api_key }}
  zt_api_key: {{ .Values.zt_api_key | b64enc | quote }}
  {{- end }}
  zt_private_key: {{ .Values.zt_private_key | b64enc | quote }}
