apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nix-hydra.fullname" . }}
  labels:
    app: {{ template "nix-hydra.name" . }}
    chart: {{ template "nix-hydra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  hydra_dbi: {{ (printf "dbi:Pg:dbname=%s;host=%s;user=%s;password=%s" .Values.postgresql.postgresDatabase (printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-") .Values.postgresql.postgresUser .Values.postgresql.postgresPassword) | b64enc | quote }}
