apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "nix-hydra.name" . }}
    chart: {{ template "nix-hydra.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: {{ template "nix-hydra.fullname" . }}-server
  name: {{ template "nix-hydra.fullname" . }}-sa
