apiVersion: v1
kind: Service
metadata:
  name: {{ template "nix-hydra.fullname" . }}
  labels:
    app: {{ template "nix-hydra.name" . }}
    chart: {{ template "nix-hydra.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: hydra-ui
    - port: 2222
      targetPort: 80
      protocol: TCP
      name: hydra-ssh-key
  selector:
    app: {{ template "nix-hydra.name" . }}
    component: {{ template "nix-hydra.fullname" . }}-server
    release: {{ .Release.Name }}
